#!/usr/bin/env python2

'''
adapted from https://github.com/HamedMP/ImageFlow/blob/master/example_project/input_data.py
'''
import tensorflow as tf
import imageflow
import glob
import os

DATA_DIRECTORY = '/home/jared/CarHawk/data' 

def read_images(path):
	print 'reading images from', path
	images     = []
	reader     = tf.WholeFileReader()
	png_files  = glob.glob(os.path.join(path, '*.png'))
	png_file_q = tf.train.string_input_producer(png_files)
	pkey, pval = reader.read(png_file_q)
	p_image    = tf.image.decode_png(pval)
	
	with tf.Session() as sess:
		coord   = tf.train.Coordinator()
		threads	= tf.train.start_queue_runners(coord=coord)
		for i in range(len(png_files)):
			png = p_image.eval()
			images.append(png)
		coord.request_stop()
		coord.join(threads)
	return images

def main():
	#files = [os.path.join(DATA_DIRECTORY, 'training.tfrecords')]
	#read_and_decode(files)	
	validation = read_images('/home/jared/CarHawk/images/test_all/')
	train_c0   = read_images('/home/jared/CarHawk/images/train_all/c0')
	train_c1   = read_images('/home/jared/CarHawk/images/train_all/c1')
	train_c2   = read_images('/home/jared/CarHawk/images/train_all/c2')
	train_c3   = read_images('/home/jared/CarHawk/images/train_all/c3')
	train_c4   = read_images('/home/jared/CarHawk/images/train_all/c4')
	train_c5   = read_images('/home/jared/CarHawk/images/train_all/c5')
	train_c6   = read_images('/home/jared/CarHawk/images/train_all/c6')
	train_c7   = read_images('/home/jared/CarHawk/images/train_all/c7')
	train_c8   = read_images('/home/jared/CarHawk/images/train_all/c8')
	train_c9   = read_images('/home/jared/CarHawk/images/train_all/c9')

if __name__=='__main__': main()
